/** Keep in sync with src/lib/site-fonts.ts ids. */
export const DISPLAY_FONT_IDS = [
  "marker",
  "nunito",
  "figtree",
  "fredoka",
  "comic-neue",
  "kalam",
  "patrick-hand",
  "indie-flower",
  "caveat",
  "architects",
  "shadows",
  "amatic",
  "gloria",
  "handlee",
  "rock-salt",
  "bangers",
  "bebas",
  "anton",
  "oswald",
  "luckiest",
  "bungee",
  "londrina",
  "shrikhand",
  "righteous",
  "spicy-rice",
  "chicle",
  "bagel",
  "black-ops",
  "russo",
  "creepster",
  "nosifer",
  "eater",
  "bungee-shade",
  "monoton",
  "wet-paint",
  "press-start",
  "butcherman",
  "fascinate",
  "fontdiner",
  "special-elite",
  "tilt-prism",
  "pacifico",
  "lobster",
  "great-vibes",
  "playfair",
  "abril",
  "cinzel",
] as const;

export type DisplayFontId = (typeof DISPLAY_FONT_IDS)[number];
