ALTER TABLE `Client` ADD COLUMN `phone` VARCHAR(40) NULL,
    ADD COLUMN `avatarUrl` LONGTEXT NULL,
    ADD COLUMN `addressLine1` VARCHAR(200) NULL,
    ADD COLUMN `addressLine2` VARCHAR(200) NULL,
    ADD COLUMN `city` VARCHAR(120) NULL,
    ADD COLUMN `state` VARCHAR(120) NULL,
    ADD COLUMN `postalCode` VARCHAR(40) NULL,
    ADD COLUMN `country` VARCHAR(80) NULL;
